[theme]
primaryColor = "#4CAF50"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[general]
favicon = "https://raw.githubusercontent.com/natuone123/growthlens-app/main/.streamlit/favicon.png"